(source gnu)
(source melpa)

(depends-on "cask")

(depends-on "magit")
(depends-on "ace-jump-mode")
(depends-on "ace-window")
(depends-on "auto-complete")
(depends-on "change-inner")
(depends-on "discover")
(depends-on "expand-region")
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "fullframe")
(depends-on "ido-vertical-mode")
(depends-on "jedi")
(depends-on "move-text")
(depends-on "projectile")
(depends-on "smartparens")
(depends-on "smartscan")
(depends-on "smex")
(depends-on "yasnippet")
