(source gnu)
(source melpa)

(depends-on "cask")

(depends-on "ace-jump-mode")
(depends-on "auto-complete")
(depends-on "expand-region")
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "fullframe")
(depends-on "ido-vertical-mode")
(depends-on "jedi")
(depends-on "magit")
(depends-on "move-text")
(depends-on "multiple-cursors")
(depends-on "projectile")
(depends-on "yasnippet")
